# Generated by Django 3.2.16 on 2023-02-12 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leftonreadapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('RE', 'Reading'), ('TR', 'To Read'), ('CO', 'Completed')], default='TR', max_length=2)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbookreading',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='userbookreading',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userbooktoread',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='userbooktoread',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_written',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserBookCompleted',
        ),
        migrations.DeleteModel(
            name='UserBookReading',
        ),
        migrations.DeleteModel(
            name='UserBookToRead',
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leftonreadapi.book'),
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='books', through='leftonreadapi.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
