# Generated by Django 3.2.16 on 2023-02-12 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leftonreadapi', '0002_auto_20230212_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='books', through='leftonreadapi.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
