# Generated by Django 3.2.16 on 2023-02-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0005_auto_20230213_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_written',
            new_name='publish_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
