# Generated by Django 3.2.16 on 2023-02-14 02:59

from django.db import migrations

import csv
import datetime

# https://stackoverflow.com/questions/9235853/convert-bibtex-file-to-database-entries-using-python
def read_csv(app, schema_editor):

  book_model = app.get_model('leftonreadapi', 'Book')

  with open('./book-data/leftonread_1-10.csv', mode='r', encoding='utf-8-sig') as file:
    reader = csv.DictReader(file)
    
    for row in reader:
      date = datetime.date(int(row['pub_year']), 1, 1)
      word_count = int(row['word_count'])
      difficulty = 'E'

      book_model.objects.create(
        title=row['title'],
        author=row['author'],
        language='EN',
        word_count=word_count,
        difficulty=difficulty,
        cover_image_url=row['cover_image_url'],
        description=row['description'],
        publish_date=date,
      )


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0006_auto_20230213_2337'),
    ]

    operations = [
        migrations.RunPython(read_csv),
    ]
