# Generated by Django 3.2.16 on 2023-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0007_custom_book_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
