# Generated by Django 3.2.16 on 2023-02-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0008_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(blank=True, choices=[('ADV', 'Adventure'), ('MYS', 'Mystery'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('SCF', 'Sci-Fi'), ('DYS', 'Dystopian'), ('CON', 'Contemporary')], max_length=3, null=True),
        ),
    ]
