# Generated by Django 3.2.16 on 2023-02-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0010_auto_20230216_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
