# Generated by Django 3.2.16 on 2023-02-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0011_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='leftonreadapi.profile'),
        ),
    ]
