# Generated by Django 3.2.16 on 2023-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0013_auto_20230317_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_available_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
