# Generated by Django 3.2.16 on 2023-03-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0016_remove_book_users_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_available_url',
            new_name='amazon_url',
        ),
        migrations.AddField(
            model_name='book',
            name='audible_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='kindle_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
