# Generated by Django 3.2.16 on 2023-03-22 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0017_auto_20230321_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
