# Generated by Django 3.2.16 on 2023-03-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0018_alter_genre_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(blank=True, choices=[('ADV', 'Adventure'), ('MYS', 'Mystery'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('SCF', 'Sci-Fi'), ('DYS', 'Dystopian'), ('CON', 'Contemporary'), ('DRA', 'Drama'), ('TRA', 'Tragedy')], max_length=3, null=True),
        ),
    ]
