# Generated by Django 3.2.16 on 2023-03-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0019_custom_genres'),
        ('leftonreadapi', '0020_alter_profile_profile_picture_url'),
    ]

    operations = [
    ]
