# Generated by Django 3.2.16 on 2023-03-23 21:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leftonreadapi', '0021_merge_20230323_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(blank=True, choices=[('ADV', 'Adventure'), ('MYS', 'Mystery'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('SCF', 'Sci-Fi'), ('DYS', 'Dystopian'), ('CON', 'Contemporary')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(blank=True)),
                ('goal_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
