# Generated by Django 3.2.16 on 2023-03-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0021_alter_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
