# Generated by Django 3.2.16 on 2023-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0022_auto_20230323_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='audible_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='kindle_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(blank=True, choices=[('ADV', 'Adventure'), ('MYS', 'Mystery'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('SCF', 'Sci-Fi'), ('DYS', 'Dystopian'), ('CON', 'Contemporary'), ('TRA', 'Contemporary'), ('DRA', 'Drama')], max_length=3, null=True),
        ),
    ]
