# Generated by Django 3.2.16 on 2023-03-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftonreadapi', '0023_auto_20230323_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
